// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZawartoscLodowki.Persistance.DatabaseContext;

#nullable disable

namespace ZawartoscLodowki.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607092038_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZawartoscLodowki.Domain.Assortment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssortmentKindId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AssortmentKindId");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("Assortments");
                });

            modelBuilder.Entity("ZawartoscLodowki.Domain.AssortmentKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssortmentKinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Szynka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pieczywo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sok"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Warzywa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Owoce"
                        });
                });

            modelBuilder.Entity("ZawartoscLodowki.Domain.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasureUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Szt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "L"
                        });
                });

            modelBuilder.Entity("ZawartoscLodowki.Domain.Assortment", b =>
                {
                    b.HasOne("ZawartoscLodowki.Domain.AssortmentKind", "AssortmentKind")
                        .WithMany()
                        .HasForeignKey("AssortmentKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZawartoscLodowki.Domain.MeasureUnit", "MeasureUnit")
                        .WithMany()
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssortmentKind");

                    b.Navigation("MeasureUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
